### PR TITLE
docs: update API functions in README

### PR DESCRIPTION
**Pull request by yuki-2000**
In class AppPixivAPI(BasePixivAPI), functions written in README are old, so I update functions texts based on the pixivpy3/aapi.py on 2022/2/22.

Also I requset someone to write summary comments on the function `user_related()` and `search_user()` in both `aapi.py` and `REDME.md` because there is no comments. 
(I hope someone write all summary comment in English.)

I have never made a pull request in upbit/pixivpy and even in GitHub before, so if there is a mistake, please fix it.

### CODE REVIEW

**Comment by upbit** [comment]
Thanks for submitting. In fact, when updating the README, I specifically hide some unnecessary public parameters, to make the interface look clearer.

So most of the interface contains, and there are no meaningful parameters, we can remove from the README. eg: `req_auth=True`, `filter="for_ios"`

**Comment by upbit** [comment]
The README I wrote earlier was relatively simple and did not give a good guide. Feel free to contact me if there is a better introduction on how to use the API.

**Comment by yuki-2000** [comment]
Thank you for quick reply.

Fixing README, I thought you seemed to delete no meaningful parameters and it is correct.
What I wanted to do in this commit is 
1. Add new functions such as `user_related()`, ` illust_comments()`  and `illust_new()`
2. Update the comment about argument such as `## type: [illust, manga]` in `user_illusts()` 

Adding rest parameters is not my aim. 

May I fix only number 1 and 2 above and commmit it again?
and I suggest delete `self` in readme to look clearer. What do you think about this.

**Comment by upbit** [comment]
You are very welcome to submit optimizations to the README docs, both `1` and `2` above, and delete `self,` is OK

**Pull request closed without merging**
