### PR TITLE
Download directly to filelike object

### PR DESCRIPTION
**Pull request by Nachtalb**
This enables us to download files directly into memory with io.BytesIO.
This can be used eg. when downloading an ugoira zip which we then want
to process further instead of saving it to the disk.

If #101 gets merged I'll be updating this and vice versa.

Example application of this feature.
```python
out = BytesIO()
if app.download(url='some_url', file_obj=out)
    out.seek(0)
    with ZipFile(out) as zip:
	    zip.extractall('foo/bar/')
```

### CODE REVIEW

**Comment by upbit** [comment]
Great idea!

Can we implement the fname, to support filename or file handle through one variable? (like [numpy.savetxt](https://github.com/numpy/numpy/blob/v1.17.0/numpy/lib/npyio.py#L1198-L1446))

```
fname : filename or file handle
  If the filename ends in .gz, the file is automatically saved in compressed gzip format. loadtxt understands gzipped files transparently.
```

**Comment by upbit** [comment]
By the way, please do not delete the `name` parameter, otherwise provide a new `fname` to support this feature (because the `name` parameter has been provided in the previous version, the deletion may cause the old version to be incompatible)

**Comment by Nachtalb** [comment]
> By the way, please do not delete the `name` parameter, otherwise provide a new `fname` to support this feature.

So you mean something like this? 
```python
def download(self, url, prefix='', fname=None, replace=False, referer=...):
    if fname is filelike:
        do filelike.write stuff
    else:
        if fname includes filename:
            path, name = dirname(fname), basename(fname)
		else:
			path = fname
			name = filename from url
		save to path/name
```

**Comment by Nachtalb** [comment]
Also as you told me in #101 this framework still supports python 2 so I'll add support for that here as well.

**Comment by upbit** [comment]
En, I mean add `fname` but keep `name`, make download() API works both:

> api.download(url, name=None)
> api.download(url, name='xxx.jpg')
> api.download(url, fname=open('xxx.jpg', 'w'))

```py
def download(self, url, prefix='', path=os.path.curdir, name=None, fname=None,
                 replace=False, file_obj=None, referer='https://app-api.pixiv.net/'):
    fid = None
    if (fname is None) and (name is None):
        # Keep the original features: name and fname are not passed, use the name in the url
        filename = prefix + os.path.basename(url)
        if (not os.path.exists(filename)) or replace:
            fid = open(filename)
            ...
    elif isinstance(fname, basestring):
        filename = fname
        if (not os.path.exists(filename)) or replace:
            fid = open(filename)
            ...
    else:
        # file handler
        fid = fname
    
    ...
```

**Comment by Nachtalb** [comment]
@upbit I have not added those cases:

```python
api.download(url, name=None)
api.download(url, name='xxx.jpg')
api.download(url, fname='xxx.jpg')
api.download(url, fname=open('xxx.jpg', 'w'))
```

**Comment by upbit** [comment]
Thanks for the contribution! Merged.

It's fine, I will check them later.

**Pull request merged**
