### PR TITLE
Replace imp with importlib

### PR DESCRIPTION
**Pull request by eggplants**
Closes: #218

### CODE REVIEW

**Comment by Xdynix** [comment]
Wondering why we need these `importlib.reload(sys)`. Anyone has context?

**Comment by eggplants** [comment]
I'm willing to to omit it. (just leaving it in to maintain the current behavior)

**Comment by eggplants** [comment]
🤔 

image

**Comment by Xdynix** [comment]
I guess it's an error response, caused by too frequency calling (by Github Action).

**Comment by eggplants** [comment]
After merging #213, I am going to merge upstream (upbit:master) and re-run CI.

**Comment by upbit** [comment]
`imp.reload(sys)` is used to switch UTF-8 character set, do we still need this code after we deprecated Python 2?

**Comment by upbit** [comment]
Thank you for your contribution. Merged

**Pull request merged**
